### ISSUE TITLE
Incorrect type for channel object

### ISSUE THREAD

**Issue by jakebloom** [sendbird/SendBird-Desk-SDK-JavaScript#2]
Hi team,

The channel object is listed as `Object` when in reality it should inherit from Sendbird's `GroupChannel` type. It would be great if this could be fixed.

https://github.com/sendbird/SendBird-Desk-SDK-JavaScript/blob/master/SendBird.Desk.d.ts#L73

Thanks team!

**Comment by chrisallo** [comment]
We recognize that some object types have dependency on SendBird SDK. As you know, TypeScript file works as a reference and does not provides the reference over the SDK itself. So we put it as Object instead of GroupChannel or other SendBird-owned types.
